# Tasks that should be run once to alter data in production.

namespace :onetime do
  # Add new categories.
  #
  # This is idempotent so it is safe to run more than once
  task add_categories: :environment do
    Category.transaction do
      renamed_categories = [
        %w(Shelter Housing),
        %w(Medical Health)
      ]
      renamed_categories.each do |old, new|
        Category.where(name: old).update(name: new)
      end

      categories = [
        'Emergency',
        'Immediate Safety',
        'Help Escape Violence',
        'Psychiatric Emergency Services',
        'Food',
        'Food Delivery',
        'Food Pantry',
        'Free Meals',
        'Food Benefits',
        'Help Pay for Food',
        'Food Benefits',
        'Housing',
        'Temporary Shelter',
        'Help Pay For Housing',
        'Help Pay for Housing',
        'Help Pay for Utilities',
        'Help Pay for Internet or Phone',
        'Home & Renters Insurance',
        'Housing Vouchers',
        'Long-Term Housing',
        'Assisted Living',
        'Independent Living',
        'Nursing Home',
        'Public Housing',
        'Safe Housing',
        'Short-Term Housing',
        'Sober Living',
        'Goods',
        'Clothing',
        'Clothes for School',
        'Clothes for Work',
        'Clothing Vouchers',
        'Home Goods',
        'Medical Supplies',
        'Personal Safety',
        'Transit',
        'Bus Passes',
        'Help Pay for Transit',
        'Health',
        'Addiction & Recovery',
        'Dental Care',
        'Health Education',
        'Daily Life Skills',
        'Disease Management',
        'Family Planning',
        'Nutrition Education',
        'Parenting Education',
        'Sex Education',
        'Understand Disability',
        'Understand Mental Health',
        'Help Pay for Healthcare',
        'Disability Benefits',
        'Discounted Healthcare',
        'Health Insurance',
        'Prescription Assistance',
        'Medical Supplies',
        'Transportation for Healthcare',
        'Medical Care',
        'Primary Care',
        'Birth Control',
        'Checkup & Test',
        'Disability Screening',
        'Disease Screening',
        'Hearing Tests',
        'Mental Health Evaluation',
        'Pregnancy Tests',
        'Fertility',
        'Maternity Care',
        'Personal Hygiene',
        'Postnatal Care',
        'Prevent & Treat',
        'Counseling',
        'HIV Treatment',
        'Pain Management',
        'Disease Management',
        'Physical Therapy',
        'Specialized Therapy',
        'Vaccinations',
        'Mental Health Care',
        'Anger Management',
        'Bereavement',
        'Counseling',
        'Group Therapy',
        'Substance Abuse Counseling',
        'Family Counseling',
        'Individual Counseling',
        'Medicatons for Mental Health',
        'Mental Health Evaluation',
        'Psychiatric Emergency Services',
        'Drug Testing',
        'Hospice',
        'Pain Management',
        'Vision Care',
        'Money',
        'Government Benefits',
        'Disability Benefits',
        'Food Benefits',
        'Retirement Benefits',
        'Understand Government Programs',
        'Unemployment Benefits',
        'Financial Education',
        'Insurance',
        'Health Insurance',
        'Tax Preparation',
        'Care',
        'Daytime Care',
        'Adult Daycare',
        'After School Care',
        'Before School Care',
        'Childcare',
        'Help Find Childcare',
        'Help Pay for Childcare',
        'Day Camp',
        'Preschool',
        'Recreation',
        'Relief for Caregivers',
        'End-of-Life Care',
        'Navigating the System',
        'Help Fill out Forms',
        'Help Find Childcare',
        'Help Find Housing',
        'Help Find School',
        'Help Find Work',
        'Support Network',
        'Counseling',
        'Help Hotlines',
        'Home Visiting',
        'In-Home Support',
        'Mentoring',
        'One-on-One Support',
        'Peer Support',
        'Spiritual Support',
        'Support Groups',
        '12-Step',
        'Bereavement',
        'Parenting Education',
        'Virtual Support',
        'Education',
        'Help Find School',
        'Help Pay for School',
        'Books',
        'Clothes for School',
        'Financial Aid & Loans',
        'Transportation for School',
        'Supplies for School',
        'More Education',
        'Alternative Education',
        'English as a Second Language (ESL)',
        'Financial Education',
        'Foreign Languages',
        'GED/High-School Equivalency',
        'Supported Employment',
        'Special Education',
        'Tutoring',
        'Preschool',
        'Screening & Exams',
        'Citizenship & Immigration',
        'Skills & Training',
        'Basic Literacy',
        'Computer Class',
        'Daily Life Skills',
        'Interview Training',
        'Resume Development',
        'Skills Assessment',
        'Specialized Training',
        'Work',
        'Help Find Work',
        'Job Placement',
        'Supported Employment',
        'Help Pay for Work Expenses',
        'Clothes for Work',
        'Workplace Rights',
        'Legal',
        'Advocacy & Legal Aid',
        'Citizenship & Immigration',
        'Discrimination & Civil Rights',
        'Guardianship',
        'Identification Recovery',
        'Understand Government Programs',
        'Mediation',
        'Notary',
        'Representation',
        'Translation & Interpretation',
        'Homelessness Essentials',
        'Hygiene',
        'Toilet',
        'Shower',
        'Hygiene Supplies',
        'Waste Disposal',
        'Water',
        'Storage',
        'Drug Related Services',
        'Government Homelessness Services',
        'Technology',
        'Wifi Access',
        'Computer Access',
        'Smartphones'
      ]
      categories.each do |c|
        Category.find_or_create_by(name: c)
      end

      # Take all resources and services under old category and also tag them
      # under new category.
      cloned_categories = [
        ['Hygiene', 'Homelessness Essentials'],
        ['Technology', 'Homelessness Essentials']
      ]
      cloned_categories.each do |old, new|
        old_category = Category.find_by_name!(old)
        new_category = Category.find_by_name!(new)

        old_category.resources.each { |r| r.categories << new_category }
        old_category.services.each { |s| s.categories << new_category }
      end

      Category.all.update_all(top_level: false)
      top_level_categories = [
        'Emergency',
        'Food',
        'Housing',
        'Goods',
        'Transit',
        'Health',
        'Money',
        'Care',
        'Education',
        'Work',
        'Legal',
        'Homelessness Essentials'
      ]
      top_level_categories.each do |c|
        Category.find_by_name!(c).update(top_level: true)
      end
    end # Category.transaction
  end
end
