sudo: false

language: ruby

services:
  - docker

rvm:
- 2.3.0

cache: bundler

addons:
  # We should be using a newer version (like the latest, 9.5), but
  # this is working out-of-the-box on Travis, so we'll go with it in
  # CI for now.
  postgresql: "9.2"

env:
  - global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - SANITIZED_BRANCH=$(echo $TRAVIS_BRANCH|sed 's|/|-|g')
    - REPO=sheltertechsf/askdarcel-api

before_install:
  - nvm install 6
  - nvm use 6

install:
  # bundle install command copied from Travis's default install.bundler
  - bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
  - npm install -g newman

before_script: bundle exec rake db:create db:schema:load

script:
  - bundle exec rake rubocop spec
  - ./travis/postman.sh

after_success:
  - echo 'export DATABASE_URL="'$PRECOMPILE_DATABASE_URL'"' >> .env
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - export TAG=`if [[ -n "$TRAVIS_TAG" ]]; then echo "$TRAVIS_TAG"; else if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then echo "pull-request-$TRAVIS_PULL_REQUEST"; else if [ "$SANITIZED_BRANCH" == "master" ]; then echo "latest"; else echo "branch-$SANITIZED_BRANCH"; fi; fi; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - echo "Pushing tags for '$COMMIT', '$TAG', and 'travis-$TRAVIS_BUILD_NUMBER'"
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
